AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    TargetEnv:
        Type: String
        AllowedValues:
            - dev2
            - dev
            - qa
            - stg
            - uat
            - tp
            - prod
        Description: will create different resources depending on environments
    AppName:
        Type: String
        Description: AppName
    ComponentName:
        Type: String
        Description: The ComponentName
Resources:
    xssMatchset:
        Type: AWS::WAFRegional::XssMatchSet
        Properties:
            Name: "xssurl"
            XssMatchTuples:
                -
                    TextTransformation: "URL_DECODE"
                    FieldToMatch:
                        Type: "QUERY_STRING"
    ruleForXSS:
        Type: AWS::WAFRegional::Rule
        Properties: 
          MetricName: "defendXSS"
          Name: "DefendXSS"
          Predicates: 
            - 
                DataId: !Ref xssMatchset
                Negated: false
                Type: XssMatch

    wafUniversalMars:
        Type: AWS::WAFRegional::WebACL
        Properties: 
            DefaultAction: 
                Type: ALLOW
            MetricName: "WebappUniversalWaf"
            Name: "A WAF could be applied to all webapps"
            Rules: 
                - 
                    Action:
                        Type: BLOCK
                    Priority: 1
                    RuleId: !Ref ruleForXSS