AWSTemplateFormatVersion: "2010-09-09"
Parameters:
    TargetEnv:
        Type: String
        AllowedValues:
            - dev2
            - dev
            - qa
            - stg
            - uat
            - tp
            - prod
        Description: will create different resources depending on environments
    AppName:
        Type: String
        Description: AppName
    ComponentName:
        Type: String
        Description: The ComponentName
Resources:
    # ruleForXss:
    #     Type: AWS::WAF::Rule
    #     Properties: 
    #       MetricName: "detectXSS"
    #       Name: "DefendXSS"
    #       Predicates: 
    #         - 
    #             OnePredicate
    #             DataId: "noXss"
    #             Negated: false
    #             Type: XssMatch

    wafUniversalMars:
        Type: AWS::WAF::WebACL
        Properties: 
            DefaultAction: 
                ALLOW
            MetricName: "WebappUniversalWaf"
            Name: "A WAF could be applied to all webapps"
            Rules: 
                - "detectXSS"